### ISSUE TITLE
Simbols above bars

### ISSUE THREAD

**Issue by AgustinPardo** [ISA-tools/SequenceLogoVis#7]
Hello,

I would like to know which is the meaning of these little symbols above each bar:

![Screenshot from 2020-04-24 01-25-11](https://user-images.githubusercontent.com/14830537/80174914-80dbd500-85ca-11ea-849d-cd0b872d7d7e.png)

Regards

**Comment by proccaserra** [comment]
@AgustinPardo you can find the explanation for this part on the glyph in figure 5 on the publication by @eamonnmag . 

- [x] the bar is about the `amount of variation`
- [x] the `droplet` indicates `hydropathy`
- [x] the +/- indicates `charge`.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/517736/80190018-873e7100-860b-11ea-8a44-f4f41566d255.png">

Thx for the interest!
